export const COMPANY_REVIEWS_DATA = {
  'bastien-arfi': {
    kpiOS: { rating: '4.5', count: 327 },
    kpiGoogle: { rating: '4.2', count: 200 },
    tabs: { sansReponses: 12, negatifs: 2, aRecuperer: 5 },
    reviews: [
      {
        id: 'bastien-arfi-1',
        author: 'Jean David Lepinieux',
        rating: '4.5',
        date: '06/09/2026',
        text: "Une expérience fantastique du début à la fin ! L'équipe était professionnelle, réactive et a vraiment compris ce que je voulais atteindre a...",
        collaboratorId: 'angela-belle',
      },
      {
        id: 'bastien-arfi-2',
        author: 'Amélie Rousseau',
        rating: '4.0',
        date: '05/09/2026',
        text: "Service rapide et efficace, seul bémol le délai d'attente initial mais le résultat final était à la hauteur de nos attentes...",
        collaboratorId: 'sue-fley',
      },
      {
        id: 'bastien-arfi-3',
        author: 'Marc Villeneuve',
        rating: '3.5',
        date: '02/09/2026',
        text: "Bonne expérience globale, quelques délais de réponse mais l'équipe a su nous rassurer et répondre à toutes nos questions...",
        collaboratorId: 'angela-belle',
      },
    ],
  },
  'sofa-kingdom': {
    kpiOS: { rating: '4.7', count: 214 },
    kpiGoogle: { rating: '4.4', count: 156 },
    tabs: { sansReponses: 6, negatifs: 1, aRecuperer: 3 },
    reviews: [
      {
        id: 'sofa-kingdom-1',
        author: 'Sofia Martinez',
        rating: '5.0',
        date: '04/09/2026',
        text: 'Un accompagnement impeccable du début à la fin, je recommande vivement cette agence à tous ceux qui cherchent un service de qualité...',
        collaboratorId: 'lou-natic',
      },
      {
        id: 'sofa-kingdom-2',
        author: 'Thomas Bernard',
        rating: '4.5',
        date: '03/09/2026',
        text: "Très bonne communication tout au long du dossier, l'équipe a été disponible et à l'écoute de nos besoins...",
        collaboratorId: 'marcus-torres',
      },
      {
        id: 'sofa-kingdom-3',
        author: 'Chloé Petit',
        rating: '4.0',
        date: '01/09/2026',
        text: 'Bon suivi général, quelques imprécisions sur les délais mais le résultat final nous satisfait pleinement...',
        collaboratorId: 'lou-natic',
      },
    ],
  },
  'tech-solutions': {
    kpiOS: { rating: '4.1', count: 98 },
    kpiGoogle: { rating: '3.9', count: 74 },
    tabs: { sansReponses: 9, negatifs: 4, aRecuperer: 2 },
    reviews: [
      {
        id: 'tech-solutions-1',
        author: 'Nicolas Faure',
        rating: '4.0',
        date: '31/08/2026',
        text: "Prestation correcte dans l'ensemble, l'équipe technique a su répondre à nos demandes spécifiques...",
        collaboratorId: 'elena-vasquez',
      },
      {
        id: 'tech-solutions-2',
        author: 'Julie Lambert',
        rating: '3.0',
        date: '29/08/2026',
        text: 'Service moyen, des délais un peu longs pour obtenir un retour mais le problème a fini par être résolu...',
        collaboratorId: 'james-chen',
      },
      {
        id: 'tech-solutions-3',
        author: 'Karim Haddad',
        rating: '4.5',
        date: '27/08/2026',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute une équipe à l’écoute...',
        collaboratorId: 'elena-vasquez',
      },
    ],
  },
  'green-valley': {
    kpiOS: { rating: '4.8', count: 412 },
    kpiGoogle: { rating: '4.6', count: 289 },
    tabs: { sansReponses: 3, negatifs: 0, aRecuperer: 7 },
    reviews: [
      {
        id: 'green-valley-1',
        author: 'Isabelle Moreau',
        rating: '5.0',
        date: '06/09/2026',
        text: 'Une équipe exceptionnelle qui a su nous accompagner à chaque étape avec beaucoup de patience et de professionnalisme...',
        collaboratorId: 'priya-sharma',
      },
      {
        id: 'green-valley-2',
        author: 'Antoine Girard',
        rating: '4.5',
        date: '04/09/2026',
        text: "Excellent suivi et beaucoup de transparence tout au long de la vente, je recommande sans hésiter...",
        collaboratorId: 'alex-dupont',
      },
      {
        id: 'green-valley-3',
        author: 'Laura Simon',
        rating: '4.5',
        date: '30/08/2026',
        text: 'Très bonne expérience, équipe disponible et réactive à chaque question posée...',
        collaboratorId: 'priya-sharma',
      },
    ],
  },
  'urban-nest': {
    kpiOS: { rating: '4.3', count: 156 },
    kpiGoogle: { rating: '4.0', count: 112 },
    tabs: { sansReponses: 8, negatifs: 3, aRecuperer: 4 },
    reviews: [
      {
        id: 'urban-nest-1',
        author: 'Camille Roux',
        rating: '4.5',
        date: '05/09/2026',
        text: 'Bon accompagnement dans notre recherche, quelques visites annulées mais globalement une bonne expérience...',
        collaboratorId: 'mia-johnson',
      },
      {
        id: 'urban-nest-2',
        author: 'Hugo Fontaine',
        rating: '3.5',
        date: '28/08/2026',
        text: "Service correct, le suivi aurait pu être un peu plus proactif mais nous avons trouvé ce que l'on cherchait...",
        collaboratorId: 'mia-johnson',
      },
      {
        id: 'urban-nest-3',
        author: 'Emma Leroy',
        rating: '4.5',
        date: '25/08/2026',
        text: "Très satisfaite de l'accompagnement, l'agence a été de bon conseil sur l'ensemble du dossier...",
        collaboratorId: 'sue-fley',
      },
    ],
  },
}
