// Questionnaires that were sent to a customer but never answered -- distinct
// from COMPANY_REVIEWS_DATA, which only holds reviews that were actually
// submitted. "À Récupérer" surfaces these so an owner can relaunch/resend
// before the link expires.
const SERVICES = [
  'Transaction Immobilière',
  'Location de propriété',
  'Estimation immobilière',
  'Gestion locative',
]

export const COMPANY_PENDING_REVIEWS = {
  'bastien-arfi': [
    {
      id: 'pending-bastien-arfi-1',
      author: 'Jean David Lepinieux',
      phone: '+33 06 14 82 39 57',
      email: null,
      service: SERVICES[0],
      certification: 'certifie-os',
      collaboratorId: 'angela-belle',
      sentDate: '28/08/2026',
      relanceDate: '02/09/2026',
      expiryDate: '08/09/2026',
      archived: false,
    },
    {
      id: 'pending-bastien-arfi-2',
      author: 'Amélie Rousseau',
      phone: '+33 06 22 45 67 89',
      email: null,
      service: SERVICES[1],
      certification: 'certifie-os',
      collaboratorId: 'lou-natic',
      sentDate: '30/08/2026',
      relanceDate: null,
      expiryDate: '10/09/2026',
      archived: false,
    },
    {
      id: 'pending-bastien-arfi-3',
      author: 'Marc Villeneuve',
      phone: '+33 07 55 12 34 56',
      email: 'marc.villeneuve@gmail.com',
      service: SERVICES[2],
      certification: 'standard-os',
      collaboratorId: 'angela-belle',
      sentDate: '25/08/2026',
      relanceDate: '31/08/2026',
      expiryDate: '06/09/2026',
      archived: false,
    },
    {
      id: 'pending-bastien-arfi-4',
      author: 'Claire Dubois',
      phone: '+33 06 78 90 12 34',
      email: null,
      service: SERVICES[3],
      certification: 'certifie-os',
      collaboratorId: 'james-chen',
      sentDate: '29/08/2026',
      relanceDate: '03/09/2026',
      expiryDate: '09/09/2026',
      archived: false,
    },
    {
      id: 'pending-bastien-arfi-5',
      author: 'Nicolas Faure',
      phone: '+33 07 33 44 55 66',
      email: null,
      service: SERVICES[0],
      certification: 'certifie-os',
      collaboratorId: 'sue-fley',
      sentDate: '02/09/2026',
      relanceDate: null,
      expiryDate: '13/09/2026',
      archived: false,
    },
  ],
  'sofa-kingdom': [
    {
      id: 'pending-sofa-kingdom-1',
      author: 'Sofia Martinez',
      phone: '+33 06 11 22 33 44',
      email: 'sofia.martinez@gmail.com',
      service: SERVICES[0],
      certification: 'certifie-os',
      collaboratorId: 'lou-natic',
      sentDate: '28/08/2026',
      relanceDate: '02/09/2026',
      expiryDate: '08/09/2026',
      archived: false,
    },
    {
      id: 'pending-sofa-kingdom-2',
      author: 'Thomas Bernard',
      phone: '+33 07 66 77 88 99',
      email: null,
      service: SERVICES[1],
      certification: 'standard-os',
      collaboratorId: 'marcus-torres',
      sentDate: '30/08/2026',
      relanceDate: null,
      expiryDate: '10/09/2026',
      archived: false,
    },
    {
      id: 'pending-sofa-kingdom-3',
      author: 'Chloé Petit',
      phone: '+33 06 45 56 67 78',
      email: null,
      service: SERVICES[2],
      certification: 'certifie-os',
      collaboratorId: 'lou-natic',
      sentDate: '26/08/2026',
      relanceDate: '31/08/2026',
      expiryDate: '06/09/2026',
      archived: false,
    },
  ],
  'tech-solutions': [
    {
      id: 'pending-tech-solutions-1',
      author: 'Nicolas Faure',
      phone: '+33 07 88 99 00 11',
      email: 'nicolas.faure@gmail.com',
      service: SERVICES[2],
      certification: 'certifie-os',
      collaboratorId: 'elena-vasquez',
      sentDate: '29/08/2026',
      relanceDate: '03/09/2026',
      expiryDate: '09/09/2026',
      archived: false,
    },
    {
      id: 'pending-tech-solutions-2',
      author: 'Julie Lambert',
      phone: '+33 06 99 88 77 66',
      email: null,
      service: SERVICES[0],
      certification: 'standard-os',
      collaboratorId: 'james-chen',
      sentDate: '31/08/2026',
      relanceDate: null,
      expiryDate: '11/09/2026',
      archived: false,
    },
  ],
  'green-valley': [
    {
      id: 'pending-green-valley-1',
      author: 'Isabelle Moreau',
      phone: '+33 07 12 23 34 45',
      email: null,
      service: SERVICES[0],
      certification: 'certifie-os',
      collaboratorId: 'priya-sharma',
      sentDate: '28/08/2026',
      relanceDate: '02/09/2026',
      expiryDate: '08/09/2026',
      archived: false,
    },
    {
      id: 'pending-green-valley-2',
      author: 'Antoine Girard',
      phone: '+33 06 34 45 56 67',
      email: 'antoine.girard@gmail.com',
      service: SERVICES[3],
      certification: 'certifie-os',
      collaboratorId: 'alex-dupont',
      sentDate: '30/08/2026',
      relanceDate: null,
      expiryDate: '10/09/2026',
      archived: false,
    },
    {
      id: 'pending-green-valley-3',
      author: 'Laura Simon',
      phone: '+33 07 56 67 78 89',
      email: null,
      service: SERVICES[1],
      certification: 'standard-os',
      collaboratorId: 'priya-sharma',
      sentDate: '27/08/2026',
      relanceDate: '01/09/2026',
      expiryDate: '07/09/2026',
      archived: false,
    },
    {
      id: 'pending-green-valley-4',
      author: 'Karim Haddad',
      phone: '+33 06 14 82 39 57',
      email: null,
      service: SERVICES[2],
      certification: 'certifie-os',
      collaboratorId: 'alex-dupont',
      sentDate: '01/09/2026',
      relanceDate: null,
      expiryDate: '12/09/2026',
      archived: false,
    },
  ],
  'urban-nest': [
    {
      id: 'pending-urban-nest-1',
      author: 'Camille Roux',
      phone: '+33 06 22 45 67 89',
      email: 'camille.roux@gmail.com',
      service: SERVICES[0],
      certification: 'certifie-os',
      collaboratorId: 'mia-johnson',
      sentDate: '28/08/2026',
      relanceDate: '02/09/2026',
      expiryDate: '08/09/2026',
      archived: false,
    },
    {
      id: 'pending-urban-nest-2',
      author: 'Hugo Fontaine',
      phone: '+33 07 55 12 34 56',
      email: null,
      service: SERVICES[1],
      certification: 'standard-os',
      collaboratorId: 'mia-johnson',
      sentDate: '30/08/2026',
      relanceDate: null,
      expiryDate: '10/09/2026',
      archived: false,
    },
    {
      id: 'pending-urban-nest-3',
      author: 'Emma Leroy',
      phone: '+33 06 78 90 12 34',
      email: null,
      service: SERVICES[0],
      certification: 'certifie-os',
      collaboratorId: 'sue-fley',
      sentDate: '26/08/2026',
      relanceDate: '31/08/2026',
      expiryDate: '06/09/2026',
      archived: false,
    },
  ],
}
