export const COMPANY_REVIEWS_DATA = {
  'bastien-arfi': {
    kpiOS: { rating: '4.5', count: 327 },
    kpiGoogle: { rating: '4.2', count: 200 },
    tabs: { sansReponses: 12, negatifs: 2, aRecuperer: 5 },
    reviews: [
      {
        id: 'bastien-arfi-1',
        author: 'Jean David Lepinieux',
        rating: '4.5',
        date: '06/09/2026',
        text: "Une expérience fantastique du début à la fin ! L'équipe était professionnelle, réactive et a vraiment compris ce que je voulais atteindre...",
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'bastien-arfi-2',
        author: 'Amélie Rousseau',
        rating: '4.0',
        date: '05/09/2026',
        text: "Service rapide et efficace, seul bémol le délai d'attente initial mais le résultat final était à la hauteur de nos attentes...",
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'bastien-arfi-3',
        author: 'Marc Villeneuve',
        rating: '3.5',
        date: '02/09/2026',
        text: "Bonne expérience globale, quelques délais de réponse mais l'équipe a su nous rassurer et répondre à toutes nos questions...",
        collaboratorId: 'angela-belle',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
      {
        id: 'bastien-arfi-4',
        author: 'Sophie Delacroix',
        rating: '5.0',
        date: '31/08/2026',
        text: "Un service haut de gamme, l'équipe a été à l'écoute du début à la fin et nous a trouvé le bien parfait pour notre famille...",
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'bastien-arfi-5',
        author: 'Lucas Meunier',
        rating: '2.5',
        date: '29/08/2026',
        text: "Communication difficile pendant une bonne partie du dossier, plusieurs relances nécessaires pour obtenir des nouvelles...",
        collaboratorId: 'angela-belle',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'bastien-arfi-6',
        author: 'Nina Chevalier',
        rating: '4.5',
        date: '27/08/2026',
        text: 'Très bon accompagnement dans notre projet, des conseils avisés et une équipe disponible à chaque étape...',
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
      {
        id: 'bastien-arfi-7',
        author: 'Julien Roche',
        rating: '3.0',
        date: '24/08/2026',
        text: "Expérience correcte sans plus, le bien correspondait à l'annonce mais le suivi post-visite aurait pu être plus rapide...",
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
      },
      {
        id: 'bastien-arfi-8',
        author: 'Elodie Fabre',
        rating: '5.0',
        date: '22/08/2026',
        text: 'Absolument ravie de notre collaboration avec cette agence, tout a été géré avec professionnalisme et bonne humeur...',
        collaboratorId: 'sue-fley',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'expire',
      },
      {
        id: 'bastien-arfi-9',
        author: 'Maxime Girard',
        rating: '1.5',
        date: '19/08/2026',
        text: "Déçu par le manque de suivi, plusieurs promesses non tenues concernant les délais de visite et de réponse...",
        collaboratorId: 'angela-belle',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'bastien-arfi-10',
        author: 'Charlotte Blanc',
        rating: '4.0',
        date: '17/08/2026',
        text: "Bonne agence dans l'ensemble, l'équipe a été réactive et de bon conseil tout au long de notre recherche...",
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
      {
        id: 'bastien-arfi-11',
        author: 'Baptiste Colin',
        rating: '4.5',
        date: '14/08/2026',
        text: 'Très professionnel, les visites ont été bien organisées et les documents transmis rapidement à chaque étape...',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'bastien-arfi-12',
        author: 'Manon Perrin',
        rating: '3.5',
        date: '11/08/2026',
        text: 'Expérience globalement positive, quelques imprécisions sur le dossier mais une équipe à l’écoute pour corriger le tir...',
        collaboratorId: 'sue-fley',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
      },
      {
        id: 'bastien-arfi-13',
        author: 'Théo Marchand',
        rating: '5.0',
        date: '08/08/2026',
        text: "Rien à redire, tout s'est déroulé parfaitement du premier contact jusqu'à la signature, je recommande sans hésiter...",
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
    ],
  },
  'sofa-kingdom': {
    kpiOS: { rating: '4.7', count: 214 },
    kpiGoogle: { rating: '4.4', count: 156 },
    tabs: { sansReponses: 6, negatifs: 1, aRecuperer: 3 },
    reviews: [
      {
        id: 'sofa-kingdom-1',
        author: 'Sofia Martinez',
        rating: '5.0',
        date: '04/09/2026',
        text: 'Un accompagnement impeccable du début à la fin, je recommande vivement cette agence à tous ceux qui cherchent un service de qualité...',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'sofa-kingdom-2',
        author: 'Thomas Bernard',
        rating: '4.5',
        date: '03/09/2026',
        text: "Très bonne communication tout au long du dossier, l'équipe a été disponible et à l'écoute de nos besoins...",
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'sofa-kingdom-3',
        author: 'Chloé Petit',
        rating: '4.0',
        date: '01/09/2026',
        text: 'Bon suivi général, quelques imprécisions sur les délais mais le résultat final nous satisfait pleinement...',
        collaboratorId: 'lou-natic',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
      },
    ],
  },
  'tech-solutions': {
    kpiOS: { rating: '4.1', count: 98 },
    kpiGoogle: { rating: '3.9', count: 74 },
    tabs: { sansReponses: 9, negatifs: 4, aRecuperer: 2 },
    reviews: [
      {
        id: 'tech-solutions-1',
        author: 'Nicolas Faure',
        rating: '4.0',
        date: '31/08/2026',
        text: "Prestation correcte dans l'ensemble, l'équipe technique a su répondre à nos demandes spécifiques...",
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'tech-solutions-2',
        author: 'Julie Lambert',
        rating: '3.0',
        date: '29/08/2026',
        text: 'Service moyen, des délais un peu longs pour obtenir un retour mais le problème a fini par être résolu...',
        collaboratorId: 'james-chen',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
      },
      {
        id: 'tech-solutions-3',
        author: 'Karim Haddad',
        rating: '4.5',
        date: '27/08/2026',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute une équipe à l’écoute...',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
    ],
  },
  'green-valley': {
    kpiOS: { rating: '4.8', count: 412 },
    kpiGoogle: { rating: '4.6', count: 289 },
    tabs: { sansReponses: 3, negatifs: 0, aRecuperer: 7 },
    reviews: [
      {
        id: 'green-valley-1',
        author: 'Isabelle Moreau',
        rating: '5.0',
        date: '06/09/2026',
        text: 'Une équipe exceptionnelle qui a su nous accompagner à chaque étape avec beaucoup de patience et de professionnalisme...',
        collaboratorId: 'priya-sharma',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'green-valley-2',
        author: 'Antoine Girard',
        rating: '4.5',
        date: '04/09/2026',
        text: "Excellent suivi et beaucoup de transparence tout au long de la vente, je recommande sans hésiter...",
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
      },
      {
        id: 'green-valley-3',
        author: 'Laura Simon',
        rating: '4.5',
        date: '30/08/2026',
        text: 'Très bonne expérience, équipe disponible et réactive à chaque question posée...',
        collaboratorId: 'priya-sharma',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
      },
    ],
  },
  'urban-nest': {
    kpiOS: { rating: '4.3', count: 156 },
    kpiGoogle: { rating: '4.0', count: 112 },
    tabs: { sansReponses: 8, negatifs: 3, aRecuperer: 4 },
    reviews: [
      {
        id: 'urban-nest-1',
        author: 'Camille Roux',
        rating: '4.5',
        date: '05/09/2026',
        text: 'Bon accompagnement dans notre recherche, quelques visites annulées mais globalement une bonne expérience...',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'urban-nest-2',
        author: 'Hugo Fontaine',
        rating: '3.5',
        date: '28/08/2026',
        text: "Service correct, le suivi aurait pu être un peu plus proactif mais nous avons trouvé ce que l'on cherchait...",
        collaboratorId: 'mia-johnson',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
      },
      {
        id: 'urban-nest-3',
        author: 'Emma Leroy',
        rating: '4.5',
        date: '25/08/2026',
        text: "Très satisfaite de l'accompagnement, l'agence a été de bon conseil sur l'ensemble du dossier...",
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
    ],
  },
}
