export const COMPANY_REVIEWS_DATA = {
  'bastien-arfi': {
    kpiOS: { rating: '4.5', count: 100 },
    kpiGoogle: { rating: '4.2', count: 28 },
    tabs: { sansReponses: 28, negatifs: 15, aRecuperer: 24 },
    reviews: [
      {
        id: 'bastien-arfi-1',
        author: 'Jean David Lépineux',
        rating: '4.5',
        date: '06/09/2026',
        text: 'Une expérience fantastique du début à la fin ! L\'équipe était professionel et m\'ont aider à chaque étape du processus, je recommande vivement leurs services.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-2',
        author: 'Amélie Rousseau',
        rating: '3.5',
        date: '05/09/2026',
        text: 'Service rapide et efficace, seul bémol le délai d\'attente initial mais le résultat final était à la hauteur de nos attentes.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-3',
        author: 'Sophie Marchand',
        rating: '5.0',
        date: '04/09/2026',
        text: 'Un accompagnement impeccable du début à la fin, je recommande vivement cette agence à tous ceux qui cherchent un service de qualité.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-4',
        author: 'Marc Villeneuve',
        rating: '4.0',
        date: '02/09/2026',
        text: 'Bonne expérience globale, quelques délais de réponse mais l\'équipe a su nous rassurer et répondre à toutes nos questions.',
        collaboratorId: 'angela-belle',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-5',
        author: 'Claire Dubois',
        rating: '4.5',
        date: '30/08/2026',
        text: 'Très professionnel et à l’écoute de nos besoins, un grand merci pour leur réactivité et leur suivi personnalisé.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Merci beaucoup pour votre retour, Claire ! Nous sommes ravis d\'avoir pu répondre à vos attentes et restons à votre disposition pour tout futur projet.',
      },
      {
        id: 'bastien-arfi-6',
        author: 'Chris P. Bacon',
        rating: '2.0',
        date: '06/09/2026',
        text: 'Une expérience horrible du début à la fin. Personne ne répondait à mes messages et le suivi du dossier a été très mal géré.',
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-7',
        author: 'Bruno Clement',
        rating: '2.5',
        date: '27/08/2026',
        text: 'Expérience négative, plusieurs engagements n\'ont pas été tenus et le manque de transparence était frustrant.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-8',
        author: 'Mathieu Perrin',
        rating: '2.5',
        date: '23/08/2026',
        text: 'Je ne recommande pas, le manque de professionnalisme a compliqué inutilement notre dossier.',
        collaboratorId: 'sue-fley',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Mathieu, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-9',
        author: 'Sébastien Muller',
        rating: '4.5',
        date: '21/08/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'elena-vasquez',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-10',
        author: 'Mélanie Moreau',
        rating: '5.0',
        date: '19/08/2026',
        text: 'Prestation remarquable, tout s\'est déroulé sans accroc et dans les délais annoncés.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-11',
        author: 'Benoit Thomas',
        rating: '4.5',
        date: '17/08/2026',
        text: 'Excellent suivi et beaucoup de transparence tout au long du dossier, je recommande sans hésiter.',
        collaboratorId: 'mia-johnson',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-12',
        author: 'Mathieu Martinez',
        rating: '4.0',
        date: '14/08/2026',
        text: 'Prestation remarquable, tout s\'est déroulé sans accroc et dans les délais annoncés.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-13',
        author: 'Damien Moreau',
        rating: '4.0',
        date: '11/08/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-14',
        author: 'Sophie Francois',
        rating: '3.0',
        date: '09/08/2026',
        text: 'Bon suivi général, quelques imprécisions sur les délais mais le résultat final nous satisfait.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-15',
        author: 'Cédric Fontaine',
        rating: '4.0',
        date: '06/08/2026',
        text: 'Excellent suivi et beaucoup de transparence tout au long du dossier, je recommande sans hésiter.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-16',
        author: 'Sébastien Legrand',
        rating: '4.0',
        date: '02/08/2026',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute l\'équipe, un vrai plaisir de travailler avec eux.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Sébastien, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-17',
        author: 'Alexandre Richard',
        rating: '4.0',
        date: '30/07/2026',
        text: 'Très bonne expérience, l\'équipe a su nous rassurer et nous guider tout au long du processus.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Alexandre, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-18',
        author: 'Laura Moreau',
        rating: '4.0',
        date: '27/07/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-19',
        author: 'Mélanie Martin',
        rating: '4.5',
        date: '23/07/2026',
        text: 'Très bonne expérience, l\'équipe a su nous rassurer et nous guider tout au long du processus.',
        collaboratorId: 'priya-sharma',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-20',
        author: 'Isabelle Clement',
        rating: '4.5',
        date: '20/07/2026',
        text: 'Excellent suivi et beaucoup de transparence tout au long du dossier, je recommande sans hésiter.',
        collaboratorId: 'lou-natic',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-21',
        author: 'Vincent Francois',
        rating: '3.5',
        date: '17/07/2026',
        text: 'Globalement une bonne expérience malgré quelques visites annulées et des délais serrés.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-22',
        author: 'Nathalie Robin',
        rating: '4.5',
        date: '13/07/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Nathalie, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-23',
        author: 'Audrey Simon',
        rating: '5.0',
        date: '10/07/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-24',
        author: 'Yann Mathieu',
        rating: '3.0',
        date: '08/07/2026',
        text: 'Bon suivi général, quelques imprécisions sur les délais mais le résultat final nous satisfait.',
        collaboratorId: 'james-chen',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-25',
        author: 'Julie Guerin',
        rating: '3.0',
        date: '05/07/2026',
        text: 'Service moyen, des délais un peu longs pour obtenir un retour mais le problème a fini par être résolu.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-26',
        author: 'Charlotte Lefebvre',
        rating: '4.5',
        date: '01/07/2026',
        text: 'Un accompagnement de qualité, professionnel et humain, exactement ce que nous recherchions.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-27',
        author: 'Mathieu Martin',
        rating: '2.5',
        date: '28/06/2026',
        text: 'Une expérience décevante, le suivi a été insuffisant et les délais annoncés n\'ont pas été respectés.',
        collaboratorId: 'lou-natic',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-28',
        author: 'Manon Richard',
        rating: '5.0',
        date: '25/06/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-29',
        author: 'Emma Chevalier',
        rating: '3.0',
        date: '23/06/2026',
        text: 'Prestation correcte dans l\'ensemble, l\'équipe a su répondre à nos demandes spécifiques.',
        collaboratorId: 'james-chen',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-30',
        author: 'Stéphane Dubois',
        rating: '5.0',
        date: '20/06/2026',
        text: 'Très bonne expérience, l\'équipe a su nous rassurer et nous guider tout au long du processus.',
        collaboratorId: 'sue-fley',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-31',
        author: 'Mathieu Michel',
        rating: '3.0',
        date: '18/06/2026',
        text: 'Accompagnement correct, nous aurions apprécié davantage de retours réguliers sur l\'avancement.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Mathieu, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-32',
        author: 'Alexandre Morin',
        rating: '3.5',
        date: '14/06/2026',
        text: 'Prestation correcte dans l\'ensemble, l\'équipe a su répondre à nos demandes spécifiques.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-33',
        author: 'Manon Garnier',
        rating: '5.0',
        date: '12/06/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'alex-dupont',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-34',
        author: 'Valérie Girard',
        rating: '5.0',
        date: '10/06/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-35',
        author: 'Sébastien Roussel',
        rating: '4.5',
        date: '07/06/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-36',
        author: 'Stéphane Bertrand',
        rating: '1.0',
        date: '03/06/2026',
        text: 'Une expérience décevante, le suivi a été insuffisant et les délais annoncés n\'ont pas été respectés.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-37',
        author: 'Anaïs Gauthier',
        rating: '5.0',
        date: '30/05/2026',
        text: 'Un grand merci pour leur réactivité et leur suivi personnalisé, nous sommes pleinement satisfaits.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-38',
        author: 'Damien Leroy',
        rating: '3.5',
        date: '28/05/2026',
        text: 'Service satisfaisant sans être exceptionnel, quelques points à améliorer sur la communication.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-39',
        author: 'Julien Petit',
        rating: '1.5',
        date: '24/05/2026',
        text: 'Personne ne répondait à mes messages et le suivi du dossier a été très mal géré.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Julien, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-40',
        author: 'Sébastien Bertrand',
        rating: '3.5',
        date: '20/05/2026',
        text: 'Service moyen, des délais un peu longs pour obtenir un retour mais le problème a fini par être résolu.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-41',
        author: 'Delphine Vincent',
        rating: '3.5',
        date: '17/05/2026',
        text: 'Bon suivi général, quelques imprécisions sur les délais mais le résultat final nous satisfait.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-42',
        author: 'Elodie Rousseau',
        rating: '4.0',
        date: '15/05/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'alex-dupont',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-43',
        author: 'Anaïs Francois',
        rating: '4.0',
        date: '12/05/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-44',
        author: 'Julien Bonnet',
        rating: '4.5',
        date: '10/05/2026',
        text: 'Prestation remarquable, tout s\'est déroulé sans accroc et dans les délais annoncés.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-45',
        author: 'Isabelle Nicolas',
        rating: '5.0',
        date: '08/05/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'sue-fley',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-46',
        author: 'Bruno Garnier',
        rating: '4.5',
        date: '04/05/2026',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute l\'équipe, un vrai plaisir de travailler avec eux.',
        collaboratorId: 'alex-dupont',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-47',
        author: 'Damien Henry',
        rating: '1.5',
        date: '30/04/2026',
        text: 'Personne ne répondait à mes messages et le suivi du dossier a été très mal géré.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Damien, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-48',
        author: 'Justine Simon',
        rating: '3.5',
        date: '26/04/2026',
        text: 'Expérience correcte, le suivi aurait pu être un peu plus proactif mais nous avons obtenu ce que nous cherchions.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-49',
        author: 'Chloé Gerard',
        rating: '3.5',
        date: '22/04/2026',
        text: 'Accompagnement correct, nous aurions apprécié davantage de retours réguliers sur l\'avancement.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-50',
        author: 'David Leroy',
        rating: '4.5',
        date: '18/04/2026',
        text: 'Un accompagnement de qualité, professionnel et humain, exactement ce que nous recherchions.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, David, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-51',
        author: 'Karim Robin',
        rating: '1.0',
        date: '15/04/2026',
        text: 'Expérience négative, plusieurs engagements n\'ont pas été tenus et le manque de transparence était frustrant.',
        collaboratorId: 'lou-natic',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-52',
        author: 'Frédéric Leroy',
        rating: '4.0',
        date: '11/04/2026',
        text: 'Prestation remarquable, tout s\'est déroulé sans accroc et dans les délais annoncés.',
        collaboratorId: 'elena-vasquez',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-53',
        author: 'Bruno Garcia',
        rating: '1.5',
        date: '08/04/2026',
        text: 'Une expérience décevante, le suivi a été insuffisant et les délais annoncés n\'ont pas été respectés.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-54',
        author: 'Mathieu Robin',
        rating: '3.0',
        date: '05/04/2026',
        text: 'Accompagnement correct, nous aurions apprécié davantage de retours réguliers sur l\'avancement.',
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-55',
        author: 'Manon Mathieu',
        rating: '3.0',
        date: '03/04/2026',
        text: 'Expérience correcte, le suivi aurait pu être un peu plus proactif mais nous avons obtenu ce que nous cherchions.',
        collaboratorId: 'marcus-torres',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Manon, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-56',
        author: 'Chloé André',
        rating: '1.5',
        date: '30/03/2026',
        text: 'Je ne recommande pas, le manque de professionnalisme a compliqué inutilement notre dossier.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-57',
        author: 'Cédric Thomas',
        rating: '1.0',
        date: '27/03/2026',
        text: 'Personne ne répondait à mes messages et le suivi du dossier a été très mal géré.',
        collaboratorId: 'priya-sharma',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-58',
        author: 'Stéphane Gerard',
        rating: '5.0',
        date: '23/03/2026',
        text: 'Prestation remarquable, tout s\'est déroulé sans accroc et dans les délais annoncés.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-59',
        author: 'Frédéric Francois',
        rating: '4.5',
        date: '20/03/2026',
        text: 'Je recommande vivement, l\'équipe a été très à l\'écoute et disponible pour répondre à toutes nos questions.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-60',
        author: 'Yann Masson',
        rating: '4.0',
        date: '18/03/2026',
        text: 'Un accompagnement de qualité, professionnel et humain, exactement ce que nous recherchions.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-61',
        author: 'Elodie Chevalier',
        rating: '4.0',
        date: '16/03/2026',
        text: 'Un grand merci pour leur réactivité et leur suivi personnalisé, nous sommes pleinement satisfaits.',
        collaboratorId: 'lou-natic',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-62',
        author: 'Sophie Dumont',
        rating: '3.0',
        date: '14/03/2026',
        text: 'Service satisfaisant sans être exceptionnel, quelques points à améliorer sur la communication.',
        collaboratorId: 'priya-sharma',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-63',
        author: 'Antoine Simon',
        rating: '3.5',
        date: '12/03/2026',
        text: 'Bonne expérience globale, quelques délais de réponse mais l\'équipe a su rester à l\'écoute.',
        collaboratorId: 'james-chen',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Antoine, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-64',
        author: 'Hugo Lambert',
        rating: '1.5',
        date: '09/03/2026',
        text: 'Je ne recommande pas, le manque de professionnalisme a compliqué inutilement notre dossier.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-65',
        author: 'Thomas Thomas',
        rating: '3.0',
        date: '06/03/2026',
        text: 'Accompagnement correct, nous aurions apprécié davantage de retours réguliers sur l\'avancement.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Thomas, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-66',
        author: 'Valérie Bonnet',
        rating: '4.0',
        date: '03/03/2026',
        text: 'Un grand merci pour leur réactivité et leur suivi personnalisé, nous sommes pleinement satisfaits.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-67',
        author: 'David Masson',
        rating: '4.0',
        date: '28/02/2026',
        text: 'Un accompagnement de qualité, professionnel et humain, exactement ce que nous recherchions.',
        collaboratorId: 'elena-vasquez',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-68',
        author: 'Antoine Roussel',
        rating: '4.5',
        date: '24/02/2026',
        text: 'Un accompagnement de qualité, professionnel et humain, exactement ce que nous recherchions.',
        collaboratorId: 'marcus-torres',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-69',
        author: 'Alexandre Nicolas',
        rating: '4.0',
        date: '21/02/2026',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute l\'équipe, un vrai plaisir de travailler avec eux.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-70',
        author: 'Delphine Mathieu',
        rating: '3.0',
        date: '19/02/2026',
        text: 'Bonne expérience globale, quelques délais de réponse mais l\'équipe a su rester à l\'écoute.',
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Delphine, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-71',
        author: 'Benoit Fournier',
        rating: '4.5',
        date: '16/02/2026',
        text: 'Je recommande vivement, l\'équipe a été très à l\'écoute et disponible pour répondre à toutes nos questions.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Benoit, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-72',
        author: 'Virginie David',
        rating: '4.0',
        date: '12/02/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'mia-johnson',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-73',
        author: 'Laura Bertrand',
        rating: '5.0',
        date: '10/02/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-74',
        author: 'Léa Chevalier',
        rating: '5.0',
        date: '08/02/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'priya-sharma',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-75',
        author: 'Thomas David',
        rating: '2.5',
        date: '05/02/2026',
        text: 'Service très en dessous de nos attentes, communication quasi inexistante pendant plusieurs semaines.',
        collaboratorId: 'priya-sharma',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Merci beaucoup pour votre retour, Thomas ! Nous sommes ravis d\'avoir pu répondre à vos attentes et restons à votre disposition pour tout futur projet.',
      },
      {
        id: 'bastien-arfi-76',
        author: 'Guillaume Faure',
        rating: '3.5',
        date: '02/02/2026',
        text: 'Globalement une bonne expérience malgré quelques visites annulées et des délais serrés.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Guillaume, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-77',
        author: 'Alexandre Clement',
        rating: '5.0',
        date: '30/01/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-78',
        author: 'Stéphane Masson',
        rating: '3.5',
        date: '27/01/2026',
        text: 'Accompagnement correct, nous aurions apprécié davantage de retours réguliers sur l\'avancement.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Stéphane, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-79',
        author: 'Benoit Francois',
        rating: '3.0',
        date: '23/01/2026',
        text: 'Service satisfaisant sans être exceptionnel, quelques points à améliorer sur la communication.',
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-80',
        author: 'Elodie Moreau',
        rating: '5.0',
        date: '20/01/2026',
        text: 'Je recommande vivement, l\'équipe a été très à l\'écoute et disponible pour répondre à toutes nos questions.',
        collaboratorId: 'alex-dupont',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-81',
        author: 'Maxime Moreau',
        rating: '4.5',
        date: '18/01/2026',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'james-chen',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-82',
        author: 'Isabelle Masson',
        rating: '4.5',
        date: '14/01/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-83',
        author: 'Elodie Blanc',
        rating: '5.0',
        date: '11/01/2026',
        text: 'Un grand merci pour leur réactivité et leur suivi personnalisé, nous sommes pleinement satisfaits.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-84',
        author: 'Julien Faure',
        rating: '1.0',
        date: '07/01/2026',
        text: 'Une expérience décevante, le suivi a été insuffisant et les délais annoncés n\'ont pas été respectés.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-85',
        author: 'Antoine Lambert',
        rating: '4.5',
        date: '03/01/2026',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Merci beaucoup pour votre retour, Antoine ! Nous sommes ravis d\'avoir pu répondre à vos attentes et restons à votre disposition pour tout futur projet.',
      },
      {
        id: 'bastien-arfi-86',
        author: 'Julien Muller',
        rating: '4.5',
        date: '31/12/2025',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute l\'équipe, un vrai plaisir de travailler avec eux.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-87',
        author: 'David Robert',
        rating: '4.0',
        date: '29/12/2025',
        text: 'Un accompagnement de qualité, professionnel et humain, exactement ce que nous recherchions.',
        collaboratorId: 'priya-sharma',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-88',
        author: 'Sandrine Clement',
        rating: '5.0',
        date: '25/12/2025',
        text: 'Excellent suivi et beaucoup de transparence tout au long du dossier, je recommande sans hésiter.',
        collaboratorId: 'alex-dupont',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-89',
        author: 'Loïc Durand',
        rating: '4.5',
        date: '22/12/2025',
        text: 'Prestation remarquable, tout s\'est déroulé sans accroc et dans les délais annoncés.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-90',
        author: 'Olivier Francois',
        rating: '4.0',
        date: '20/12/2025',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-91',
        author: 'Laura Mathieu',
        rating: '4.0',
        date: '18/12/2025',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-92',
        author: 'Virginie Legrand',
        rating: '5.0',
        date: '14/12/2025',
        text: 'Excellent suivi et beaucoup de transparence tout au long du dossier, je recommande sans hésiter.',
        collaboratorId: 'marcus-torres',
        source: 'google',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Merci beaucoup pour votre retour, Virginie ! Nous sommes ravis d\'avoir pu répondre à vos attentes et restons à votre disposition pour tout futur projet.',
      },
      {
        id: 'bastien-arfi-93',
        author: 'Valérie Dubois',
        rating: '4.0',
        date: '10/12/2025',
        text: 'Un grand merci pour leur réactivité et leur suivi personnalisé, nous sommes pleinement satisfaits.',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-94',
        author: 'Thomas Gerard',
        rating: '4.5',
        date: '07/12/2025',
        text: 'Service de qualité, rapide et efficace, je n\'hésiterai pas à refaire appel à eux.',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-95',
        author: 'Charlotte Lopez',
        rating: '5.0',
        date: '04/12/2025',
        text: 'Service impeccable du début à la fin, communication claire et résultats à la hauteur de nos attentes.',
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'archive',
        response: 'Charlotte, merci pour votre confiance et ce retour ! C\'était un plaisir de vous accompagner, à bientôt pour de nouveaux projets.',
      },
      {
        id: 'bastien-arfi-96',
        author: 'Caroline Robin',
        rating: '4.0',
        date: '02/12/2025',
        text: 'Une équipe exceptionnelle qui a su nous accompagner à chaque étape avec beaucoup de patience et de professionnalisme.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
        response: null,
      },
      {
        id: 'bastien-arfi-97',
        author: 'Valérie André',
        rating: '2.0',
        date: '30/11/2025',
        text: 'Personne ne répondait à mes messages et le suivi du dossier a été très mal géré.',
        collaboratorId: 'james-chen',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'archive',
        response: 'Nous vous remercions chaleureusement, Valérie, pour ce message. Toute l\'équipe apprécie votre confiance et reste disponible si besoin.',
      },
      {
        id: 'bastien-arfi-98',
        author: 'Yann Nicolas',
        rating: '3.5',
        date: '26/11/2025',
        text: 'Service moyen, des délais un peu longs pour obtenir un retour mais le problème a fini par être résolu.',
        collaboratorId: 'priya-sharma',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
      {
        id: 'bastien-arfi-99',
        author: 'Caroline Gauthier',
        rating: '4.5',
        date: '23/11/2025',
        text: 'Très bonne expérience, l\'équipe a su nous rassurer et nous guider tout au long du processus.',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
        response: null,
      },
      {
        id: 'bastien-arfi-100',
        author: 'Anaïs Roux',
        rating: '3.0',
        date: '21/11/2025',
        text: 'Expérience correcte, le suivi aurait pu être un peu plus proactif mais nous avons obtenu ce que nous cherchions.',
        collaboratorId: 'angela-belle',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'expire',
        response: null,
      },
    ],
  },
  'sofa-kingdom': {
    kpiOS: { rating: '4.7', count: 214 },
    kpiGoogle: { rating: '4.4', count: 156 },
    tabs: { sansReponses: 6, negatifs: 1, aRecuperer: 3 },
    reviews: [
      {
        id: 'sofa-kingdom-1',
        author: 'Sofia Martinez',
        rating: '5.0',
        date: '04/09/2026',
        text: 'Un accompagnement impeccable du début à la fin, je recommande vivement cette agence à tous ceux qui cherchent un service de qualité...',
        collaboratorId: 'lou-natic',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'sofa-kingdom-2',
        author: 'Thomas Bernard',
        rating: '4.5',
        date: '03/09/2026',
        text: "Très bonne communication tout au long du dossier, l'équipe a été disponible et à l'écoute de nos besoins...",
        collaboratorId: 'marcus-torres',
        source: 'opinion-system',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'sofa-kingdom-3',
        author: 'Chloé Petit',
        rating: '4.0',
        date: '01/09/2026',
        text: 'Bon suivi général, quelques imprécisions sur les délais mais le résultat final nous satisfait pleinement...',
        collaboratorId: 'lou-natic',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
      },
    ],
  },
  'tech-solutions': {
    kpiOS: { rating: '4.1', count: 98 },
    kpiGoogle: { rating: '3.9', count: 74 },
    tabs: { sansReponses: 9, negatifs: 4, aRecuperer: 2 },
    reviews: [
      {
        id: 'tech-solutions-1',
        author: 'Nicolas Faure',
        rating: '4.0',
        date: '31/08/2026',
        text: "Prestation correcte dans l'ensemble, l'équipe technique a su répondre à nos demandes spécifiques...",
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'tech-solutions-2',
        author: 'Julie Lambert',
        rating: '3.0',
        date: '29/08/2026',
        text: 'Service moyen, des délais un peu longs pour obtenir un retour mais le problème a fini par être résolu...',
        collaboratorId: 'james-chen',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
      },
      {
        id: 'tech-solutions-3',
        author: 'Karim Haddad',
        rating: '4.5',
        date: '27/08/2026',
        text: 'Très satisfait de la réactivité et du professionnalisme de toute une équipe à l’écoute...',
        collaboratorId: 'elena-vasquez',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
    ],
  },
  'green-valley': {
    kpiOS: { rating: '4.8', count: 412 },
    kpiGoogle: { rating: '4.6', count: 289 },
    tabs: { sansReponses: 3, negatifs: 0, aRecuperer: 7 },
    reviews: [
      {
        id: 'green-valley-1',
        author: 'Isabelle Moreau',
        rating: '5.0',
        date: '06/09/2026',
        text: 'Une équipe exceptionnelle qui a su nous accompagner à chaque étape avec beaucoup de patience et de professionnalisme...',
        collaboratorId: 'priya-sharma',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'sans-reponse',
      },
      {
        id: 'green-valley-2',
        author: 'Antoine Girard',
        rating: '4.5',
        date: '04/09/2026',
        text: "Excellent suivi et beaucoup de transparence tout au long de la vente, je recommande sans hésiter...",
        collaboratorId: 'alex-dupont',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'en-attente',
      },
      {
        id: 'green-valley-3',
        author: 'Laura Simon',
        rating: '4.5',
        date: '30/08/2026',
        text: 'Très bonne expérience, équipe disponible et réactive à chaque question posée...',
        collaboratorId: 'priya-sharma',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-partage',
        status: 'expire',
      },
    ],
  },
  'urban-nest': {
    kpiOS: { rating: '4.3', count: 156 },
    kpiGoogle: { rating: '4.0', count: 112 },
    tabs: { sansReponses: 8, negatifs: 3, aRecuperer: 4 },
    reviews: [
      {
        id: 'urban-nest-1',
        author: 'Camille Roux',
        rating: '4.5',
        date: '05/09/2026',
        text: 'Bon accompagnement dans notre recherche, quelques visites annulées mais globalement une bonne expérience...',
        collaboratorId: 'mia-johnson',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-non-partage',
        status: 'en-attente',
      },
      {
        id: 'urban-nest-2',
        author: 'Hugo Fontaine',
        rating: '3.5',
        date: '28/08/2026',
        text: "Service correct, le suivi aurait pu être un peu plus proactif mais nous avons trouvé ce que l'on cherchait...",
        collaboratorId: 'mia-johnson',
        source: 'google',
        certification: 'standard-os',
        googleSharing: 'google-non-partage',
        status: 'sans-reponse',
      },
      {
        id: 'urban-nest-3',
        author: 'Emma Leroy',
        rating: '4.5',
        date: '25/08/2026',
        text: "Très satisfaite de l'accompagnement, l'agence a été de bon conseil sur l'ensemble du dossier...",
        collaboratorId: 'sue-fley',
        source: 'opinion-system',
        certification: 'certifie-os',
        googleSharing: 'google-partage',
        status: 'archive',
      },
    ],
  },
}
